### ISSUE TITLE
Error message unclear

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#36] opened 2015-04-07 07:44 UTC
Form returns: Failed retrieving the metadata (code 60). Please make this error more friendly.

https://acceptatie.pscribe.nl/metadata.ashx

https://mijnnhltest.nhl.nl/simplesaml/module.php/saml/sp/metadata.php/default-sp

**Comment by baszoetekouw** [comment] 2015-04-08 12:15
Curl error 60 seems te be caused by using a self-signed (or otherwise untrusted) https certificate.  As this is perfectly valid for test and development SPs, I would like to suggest to making curl a bit more forgiving for these kinds of things, by adding:
```
curl_setopt($process, CURLOPT_SSL_VERIFYPEER, false);
```

**Comment by Tjeerd** [comment] 2015-04-17 07:29
I've updated the error message and disabled SSL certificate changes. I haven't merged it back though, because I'm wondering if you are really sure about disabling the checks? The original requirements as well as the current 'help text' state that the SSL certificate should be valid.

**Comment by teunfransen** [comment] 2015-04-17 08:01
For now we're sure about this. You're right that the original requirement state like you say, but for the test connection it is not required to have a valid SSL certificate. Later, when the form becomes part of a more automated process, this should be changed.

**Closed** 2015-04-17 08:53 UTC
